# Generated by Django 6.0.5 on 2026-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_address_alter_order_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Почётный сотрудник'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в почётных'),
        ),
    ]
