# Generated by Django 6.0.5 on 2026-06-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_options_product_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'permissions': [('request_employee_data', 'Can request employee data')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
