# Generated by Django 6.0.5 on 2026-06-11 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesscode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, которому назначен этот код. Оставьте пустым для общего кода.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
